version: "3.8"

volumes:
  mongodata:

services:
  nginx:
    image: nginx
    container_name: unijobapp_api_nginx
    ports: 
      - ${NGINX_PORT}:80
    volumes:
      - "./default-nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - "node"

  mongo-express:
    image: "mongo-express"
    container_name: unijobapp_api_mongo_express
    ports: 
      - ${MONGO_EXPRESS_PORT}:8081
    environment: 
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - "mongo"

  node:
    build: "."
    container_name: unijobapp_api_node
    working_dir: "/srv/www/unijobapp_api"
    expose: 
      - 80
    volumes:
      - ".:/srv/www/unijobapp_api"
    environment: 
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo"
    container_name: unijobapp_api_mongo
    volumes: 
      - "mongodata:/data/db"
    expose: 
      - 27017

  mailhog:
    image: mailhog/mailhog
    container_name: unijobapp_api_mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
